//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKH2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ChiTietID { get; set; }
        public Nullable<int> DonHangID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string Size { get; set; }
        public string MauSac { get; set; }
        public Nullable<double> ThueVat { get; set; }
        public Nullable<double> PhiShip { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
