//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKH2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCombo
    {
        public int ChiTietComboID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Size { get; set; }
        public string MauSac { get; set; }
    
        public virtual ComboKhuyenMai ComboKhuyenMai { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
