//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKH2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapHang
    {
        public int ChiTietNhapHangID { get; set; }
        public Nullable<int> NhapHangID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual NhapHang NhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
