//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKH2024.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopQuanAoEntities : DbContext
    {
        public ShopQuanAoEntities()
            : base("name=ShopQuanAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<NhapHang> NhapHangs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<ChiTietNhapHang> ChiTietNhapHangs { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<PhanQuyenChucNang> PhanQuyenChucNangs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietCombo> ChiTietComboes { get; set; }
        public virtual DbSet<ComboKhuyenMai> ComboKhuyenMais { get; set; }
    
        public virtual ObjectResult<spQuyenTaiKhoan_Result> spQuyenTaiKhoan(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spQuyenTaiKhoan_Result>("spQuyenTaiKhoan", iDParameter);
        }
    
        public virtual ObjectResult<GetDoanhThuTheoSanPham_Result> GetDoanhThuTheoSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDoanhThuTheoSanPham_Result>("GetDoanhThuTheoSanPham");
        }
    
        public virtual ObjectResult<spBanChay_Result> spBanChay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBanChay_Result>("spBanChay");
        }
    
        public virtual ObjectResult<GetDoanhThu_Result1> GetDoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDoanhThu_Result1>("GetDoanhThu");
        }
    }
}
