//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKH2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapHang()
        {
            this.ChiTietNhapHangs = new HashSet<ChiTietNhapHang>();
        }
    
        public int NhapHangID { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public Nullable<int> TaiKhoanID { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHangs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
